# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            conda init bash
            source ~/.bashrc
            conda create --name cupy_p39 python=3.9 cupy cudatoolkit=11.2 napari -c conda-forge
            conda activate cupy_p39
            pip install -e .

      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            conda init bash
            source ~/.bashrc
            conda activate cupy_p39
            flake8 --statistics
            pytest -v --cov
